# Generated by Django 4.1.2 on 2022-10-31 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_managers_myuser_address_myuser_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.RegexValidator('/(84|0[3|5|7|8|9])+([0-9]{8})\x08/g', message='Enter valid phone number')]),
        ),
    ]
