# Generated by Django 4.1.2 on 2022-10-31 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_myuser_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('time',)},
        ),
    ]
