# Generated by Django 4.1.2 on 2022-11-01 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_visit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
