# Generated by Django 4.1.2 on 2022-12-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_myuser_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
